name: "ci"

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      FFMPEG_DEST_DIR: /opt/ffmpeg-static
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Cache for expensive static ffmpeg binary installation
      - name: Cache for static ffmpeg
        uses: actions/cache@v3
        id: cache-ffmpeg
        with:
          path: ${{ env.FFMPEG_DEST_DIR }}
          key: ${{ runner.os }}-static-ffmpeg-v5.1.1

      # Only run this expensive step if we have a cache miss
      - if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        name: Install static ffmpeg
        run: |
          curl --connect-timeout 10 -Lv -o ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          echo "4cbbe32169c4ec79a0969d5c92cbcaff  ffmpeg.tar.xz" | md5sum --check -
          mkdir -p "$FFMPEG_DEST_DIR"
          tar -C "$FFMPEG_DEST_DIR" -xf ffmpeg.tar.xz --strip-components=1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Save Go cache paths
        id: go-cache-paths
        run: |
          echo "::set-output name=go_mod_cache::$(go env GOMODCACHE)"
          echo "::set-output name=go_cache::$(go env GOCACHE)"

      - name: Create Go module cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go_mod_cache }}
          key: ${{ runner.os }}-go_mod_cache-${{ hashFiles('go.sum') }}

      - name: Create Go cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go_cache }}
          key: ${{ runner.os }}-go_cache-${{ hashFiles('go.sum') }}

      - name: Verify module dependencies
        run: go mod verify

      - name: Test
        run: |
          export PATH="$FFMPEG_DEST_DIR":$PATH
          bash -x ./build.sh clean
          bash -x ./build.sh test

      - name: Build
        id: build
        run: |
          export PATH="$FFMPEG_DEST_DIR":$PATH
          bash -x ./build.sh clean
          bash -x ./build.sh build

      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ease-${{ github.run_number }}
          path: ${{ steps.build.outputs.artifact_path }}
